test(store): ensure busy manager goroutine is finished
Without this change, there were intermittent failures due to a non-empty
t.TempDir() directory at the end of a test:

$ go test  -run=LoadChunk$ ./snapshots/ -count=220 -failfast
--- FAIL: TestManager_LoadChunk (0.01s)
    testing.go:1225: TempDir RemoveAll cleanup: unlinkat /var/folders/.../T/TestManager_LoadChunk1472891739/001: directory not empty
FAIL
FAIL    cosmossdk.io/store/snapshots    0.177s

With this change, I can no longer reproduce the flaky failure:

$ go test -run=LoadChunk$ ./snapshots/ -count=1000 -failfast
ok      cosmossdk.io/store/snapshots    15.722s